<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Client Report</title>
        <style>
            * { box-sizing: border-box; }
            body { font-family: 'DejaVu Sans', sans-serif; color: #0f172a; margin: 24px; font-size: 10px; }
            h1 { font-size: 18px; margin: 0 0 4px; }
            .company { color: #64748b; font-size: 12px; }
            .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 16px; }
            table { width: 100%; border-collapse: collapse; margin-top: 6px; }
            th, td { border: 1px solid #cbd5e1; padding: 5px 6px; text-align: left; }
            th { background: #f1f5f9; text-transform: uppercase; font-size: 9px; letter-spacing: .03em; }
            .footer { margin-top: 32px; font-size: 10px; color: #94a3b8; text-align: center; }
        </style>
    </head>
    <body>
        @if ($company_logo)
            <div style="text-align:center; margin-bottom:12px;">
                <img src="{{ $company_logo }}" alt="logo" style="height:56px;" />
            </div>
        @endif
        <div class="header">
            <div>
                <h1>{{ $company }}</h1>
                <p class="company">Investment Client Portfolio Management System</p>
            </div>
            <div style="text-align:right;">
                <p style="font-weight:700;margin:0;">Client Report</p>
                <p class="company">{{ $clients->count() }} client(s) · Generated {{ now()->format('d/m/Y H:i') }}</p>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    @foreach ($fields as $field)
                        <th>{{ \App\Models\Client::FIELD_LABELS[$field] ?? ucwords(str_replace('_', ' ', $field)) }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($clients as $client)
                    <tr>
                        @foreach ($fields as $field)
                            <td>{{ $client->reportField($field) }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">This report was generated by the {{ $company }} system.</div>
    </body>
</html>